### ISSUE TITLE
Normalizer breaks on null values when filterReferences is enabled

### ISSUE THREAD

**Issue by westende** [carlobeltrame/hal-json-normalizer#5]
Hi,
Nice project! I was taking it for a spin and found that on the API I was dealing with that the normalizer throws an exception on null values.

The exception is thrown in `hasSingleKey` as `Object.keys` is called on `null`.

I can create a pull request if you like. Let me know. My proposal would be to check for `null` values in `isReference`.

```javascript
const json = {
  id: 2620,
  text: 'hello',
  _embedded: {
    question: null,
  },
  _links: {
    prev: {
      href: null,
    },
    self: {
      href: 'http://example.com/entity/1',
    },
  },
};

const result = normalize(json, {
  filterReferences: true,
});
```

**Comment by carlobeltrame** [comment]
Fixed in version 3.0.3. Thanks!
